<?xml version="1.0" encoding="US-ASCII"?>

<!--Author: Andreas Sauter
    Bayesian network in XMLBIF v0.3 (BayesNet Interchange Format)
 -->

<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
    <!ELEMENT BIF ( NETWORK )*>
    <!ATTLIST BIF VERSION CDATA #REQUIRED>
    <!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* )>
    <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
    <!ELEMENT OUTCOME (#PCDATA)>
    <!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )*>
    <!ELEMENT FOR (#PCDATA)>
    <!ELEMENT GIVEN (#PCDATA)>
    <!ELEMENT TABLE (#PCDATA)>
    <!ELEMENT PROPERTY (#PCDATA)>
]>

<BIF VERSION="0.3">
    <NETWORK>
        <NAME>Example with 15 variables</NAME>

        <!-- Variables-->
        <VARIABLE TYPE="nature">
            <NAME>A</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>B</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>C</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>D</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>E</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>F</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>G</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>H</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>I</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>J</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>K</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>L</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>M</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>N</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>
        <VARIABLE TYPE="nature">
            <NAME>O</NAME>
            <OUTCOME>True</OUTCOME>
            <OUTCOME>False</OUTCOME>
        </VARIABLE>

        <!-- PCTs -->
        <DEFINITION>
            <FOR>A</FOR>
            <TABLE>0.5 0.5</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>B</FOR>
            <TABLE>0.7 0.3</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>C</FOR>
            <TABLE>0.12 0.88</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>D</FOR>
            <GIVEN>A</GIVEN>
            <TABLE>0.01 0.99 0.99 0.01</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>E</FOR>
            <GIVEN>B</GIVEN>
            <GIVEN>D</GIVEN>
            <TABLE>0.95 0.05 0.95 0.05 0.95 0.05 0.05 0.95</TABLE> <!-- Order: Rain?, Sprinkler?, Wet Grass?-->
        </DEFINITION>
        <DEFINITION>
            <FOR>F</FOR>
            <GIVEN>B</GIVEN>
            <GIVEN>C</GIVEN>
            <TABLE>0.98 0.02 0.02 0.98 0.02 0.98 0.02 0.98</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>G</FOR>
            <GIVEN>B</GIVEN>
            <GIVEN>E</GIVEN>
            <TABLE>0.7 0.3 0.4 0.6 0.65 0.35 0.87 0.13</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>H</FOR>
            <GIVEN>A</GIVEN>
            <GIVEN>C</GIVEN>
            <TABLE>0.4 0.6 0.2 0.8 0.5 0.5 0.81 0.19</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>I</FOR>
            <GIVEN>F</GIVEN>
            <TABLE>0.06 0.94 0.55 0.45</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>J</FOR>
            <GIVEN>G</GIVEN>
            <TABLE>0.01 0.99 0.99 0.01</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>K</FOR>
            <GIVEN>F</GIVEN>
            <GIVEN>A</GIVEN>
            <TABLE>0.18 0.82 0.99 0.01 0.55 0.45 0.7 0.3</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>L</FOR>
            <GIVEN>A</GIVEN>
            <GIVEN>C</GIVEN>
            <TABLE>0.76 0.24 0.5 0.5 0.8 0.2 0.9 0.1</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>M</FOR>
            <GIVEN>L</GIVEN>
            <GIVEN>A</GIVEN>
            <TABLE>0.1 0.9 0.99 0.01 0.5 0.5 0.67 0.33</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>N</FOR>
            <GIVEN>K</GIVEN>
            <GIVEN>L</GIVEN>
            <TABLE>0.5 0.5 0.4 0.6 0.3 0.7 0.2 0.8</TABLE>
        </DEFINITION>
        <DEFINITION>
            <FOR>O</FOR>
            <GIVEN>M</GIVEN>
            <TABLE>0.18 0.82 0.99 0.01</TABLE>
        </DEFINITION>
    </NETWORK>
</BIF>